### ISSUE TITLE
remove Quest.queue and QuestFactory.createQuest

### ISSUE THREAD

**Issue by waynehoover** [rabbitholegg/quest-protocol#157]
The old flow of creating a quest and then calling queue on the quest contract have been depricated. We should remove these functions and move all tests to the new createQuestAndQueue flow.

**Comment by Quazia** [comment]
Follow [this pattern](https://github.com/rabbitholegg/quest-protocol/pull/155/files#diff-0ab66a42ee45292a59b93963096509787f6df788cb631546fddd444426a1ffddR451-R467) for the update to `createQuestAndQueue`

**Comment by Quazia** [comment]
There's also a `Quest1155.queue()`  do we want to try and break down that pattern to have more parity with the standard `Quest` approach? That's going to be a larger chunk of work so if we want to go down that path I'll capture separately and handle that later in the week. My instinct is it's not super important to make that change now.
