### ISSUE TITLE
remove QuestFactory.mintReceipt and Quest.claim

### ISSUE THREAD

**Issue by waynehoover** [rabbitholegg/quest-protocol#158]
We no longer mint receipts so we can remove mintReceipt and the associated claim function on the quest contract.

There also might be other places we do receipt related things, let's find those and remove them too.

**Comment by Quazia** [comment]
Looks like we can remove the `_calculateRewards` internal and simplify the logic around this in the same PR. Implies a minor tweak to [single claim](https://github.com/rabbitholegg/quest-protocol/pull/155/files#diff-c312efc821de97d7f8ff7b812308d9d1ac7a6c4644b2880114e3ecc4be18de8bR156)
