### ISSUE TITLE
Migrate tests to foundry

### ISSUE THREAD

**Issue by waynehoover** [rabbitholegg/quest-protocol#159]
We are currently using hardhat to run our tests, let's start migrating them to foundry one by one. This should be done after https://github.com/rabbitholegg/quest-protocol/pull/155 is merged.

**Comment by Quazia** [comment]
When migrating over let's pay special mind to standardization of language. For example, in some places we say `totalRewards`, in others we say `totalParticipants` . As much as is possible let's try and use repeated language. Also it makes sense to have `utils` folder that stores a lot of the repeated deployment boilerplate. Not optimizations that make sense patching onto `hardhat` but when we make the switch, good to keep these optimizations front-of-mind.
