### ISSUE TITLE
Investigate if we can remove QuestTerminalKey

### ISSUE THREAD

**Issue by waynehoover** [rabbitholegg/quest-protocol#162]
Do we need to keep this function? `function doDiscountedFee` if not then we can remove the quest terminal key its spec and this function.

**Comment by Quazia** [comment]
Note to self: look more into ticket vs key vs receipt. Where is each being used? Make sure to remove any of these that arn't being used and properly document how the remaining ones are being used.

**Comment by Quazia** [comment]
Got the go-ahead to axe this - going to start the removal this afternoon.
