### ISSUE TITLE
Only use interfaces in QuestFactory

### ISSUE THREAD

**Issue by waynehoover** [rabbitholegg/quest-protocol#168]
Instead of importing Quest.sol and Quest1155.sol in QuestFactory let's just use the interfaces instead. Look at https://github.com/rabbitholegg/quest-protocol/pull/152/commits/52b682ee23c438be158b1dcc74b284c7b10c60c2#diff-46d8d9ffae356f90bd43e36eef9e04ca41262e025e815f70e7434b80412bdf4e and the commits after for inspiration.

**Comment by Quazia** [comment]
Yeah - I think we want to use interfaces vs instantiation in all possible places (even going as far as to make utility interfaces for external contracts as needed) also ideally if we could collapse the interface for `Quest` and `Quest1155` into a single function that would be ideal. We'd probably need a bytes param to tuck some of the variation into but I think long term that type of pattern is going to be the most extensible. Encoding a bytes param into custom data on a per quest contract basis isn't going to be that heavy.

**Comment by Quazia** [comment]
For now I'll start with just the basic interface replacements though, we can discuss the other points external to the completion of this more granular issue.
