### ISSUE TITLE
Set pragma to solidity 0.8.19

### ISSUE THREAD

**Issue by waynehoover** [rabbitholegg/quest-protocol#183]
Instead of pinning to minor version, all our contracts should be set to `0.8.19`

i.e. change all pragmas to:
`pragma solidity 0.8.19;`

Other EVM chains don't support the push0 opcode in 0.8.20+ yet: https://www.evmdiff.com/features?name=PUSH0&kind=opcode

**Comment by Quazia** [comment]
I agree, I like firmly pegged versioning in general, but especially so given that potential issue.

It looks like a lot of our dependencies (Sablier, @prb/math) use `pragma solidity >=0.8.19` so something to be mindful of around the puch0 opcode.

**Comment by Rajiv620019** [comment]
Hey is there anyone working on this issue? Can I get approval to work on it?
